<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-UILR0OR" name="Test_firefox" tests="3" failures="1" timestamp="11 Aug 2019 10:02:45 GMT" time="40.939" errors="0">
  <testcase name="@AfterMethod closeAppn" time="0.0" classname="scripts.InvalidLogin">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at generic.ScreenShot.getPhoto(ScreenShot.java:28)
	at generic.Generic_Test.closeAppn(Generic_Test.java:43)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod closeAppn -->
  <testcase name="@BeforeMethod openAppn" time="0.0" classname="scripts.ValidLoginLogout">
    <skipped/>
  </testcase> <!-- @BeforeMethod openAppn -->
  <testcase name="@AfterMethod closeAppn" time="0.0" classname="scripts.ValidLoginLogout">
    <skipped/>
  </testcase> <!-- @AfterMethod closeAppn -->
  <testcase name="login" time="12.236" classname="scripts.VerifyActitimeVersion"/>
  <testcase name="login" time="6.036" classname="scripts.InvalidLogin">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at generic.Base_page.verifyTitle(Base_page.java:32)
	at scripts.InvalidLogin.login(InvalidLogin.java:28)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login" time="0.0" classname="scripts.ValidLoginLogout">
    <skipped/>
  </testcase> <!-- login -->
</testsuite> <!-- Test_firefox -->
